### ISSUE TITLE
HorizontalTail variable issues

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#1]
@mayork this is for D8_HT_simple_profile. 
Firstly the horizontal tail angle of attack variable is in the WingPerformance model:
```python
class WingPerformance(Model):
 ...
        alpha   = Variable('\\alpha', '-', 'Horizontal tail angle of attack')
```
which is extremely odd. This is proving to be an issue because the Wing in the Wing_simple_performance doesn't have this variable, whereas the Wing in D8_HT has it. This should definitely be within HTP. This might require moving some code around. 

Also, I am puzzled by the set of constraints:
```python
climb['C_{L_h}'] <= 1.1*climb['C_{L_{ah}}']*climb['\\alpha'],
climb['C_{L_h}'] >= 0.9*climb['C_{L_{ah}}']*climb['\\alpha'],
```
Why isn't this a signomial equality instead of being in these odd bounds? 

We can probably talk about these during the meeting tomorrow, but thought I should note them down in advance.

**Comment by mayork** [comment]
yep this was all done intentionally. The alpha variable in wing performance should read wing angle of attack, I'll just move it back to the HT model. I didn't realize the other wing model didn't have an AOA variable (seems like something worth adding).

the HT CLh isn't set as an equality in an effort, albeit weak, to capture the fact that you can trim the elevator to make minor lift changes while in a steady flight condition. Hence, i allow for some variation in CLh.

**Comment by mayork** [comment]
the fix is pushed i'm closing the issue

**Comment by 1ozturkbe** [comment]
Btw, the other wing has an \\alpha_w variable which describes the angle of attack. But again, it's not \\alpha, which is the horizontal tail angle of attack. Also, it should probably be named \\alpha_{ht}. Anyways, I can edit this when I integrate the D8_HT with CFP_Fuselage.

**Comment by 1ozturkbe** [comment]
@mayork the fix isn't pushed.

**Comment by mayork** [comment]
now it is. sorry, there was merge conflict so the push didn't go through the first time

**Comment by mayork** [comment]
also...if you use the empennage file I already integrated the HT and VT a couple days ago

**Comment by 1ozturkbe** [comment]
Thanks!
Yeah, I saw D8_empennage.py! I had fixed the typos hahaha; I'm a little OCD.

**Comment by 1ozturkbe** [comment]
Wait I'm confused. Why isn't horizontal tail alpha still not in HTPerformance? I pulled the latest version and it is still in WingP.

**Comment by mayork** [comment]
sorry i didn't push the D8 tail, just the generic tail

**Comment by 1ozturkbe** [comment]
Haha, I should have realized this. I was looking at your merge and saw only what I had pushed. Should have looked at the other commits more closely. 
Great, now we can close this.

**Comment by 1ozturkbe** [comment]
There are still internal inconsistencies in D8_HT model. 
Eg. 
```python
climb['C_{L}'] == 2*3.14*climb['\\alpha'],
cruise['C_{L}'] == 2*3.14*cruise['\\alpha'],
```
These equations do not make sense. @mayork this sets the C_{L} of the wing, with the \\alpha of the horizontal tail. Definitely not ok :/

**Comment by 1ozturkbe** [comment]
I have fixed. Will push changes.

**Comment by mayork** [comment]
i did that because the wing and HT should be at the same alpha assuming steady flight

**Comment by 1ozturkbe** [comment]
That's tricky, because they are not both fixed to the aircraft with the same geometric angles of attack. As an example, for JHO, the wing is fixed to the a/c with a 4degree incidence angle, whereas the horizontal tail is neutral to the body axis (should even have downward incidence technically). 

This means we need another variable. It might involve having \\alpha be an aircraftP variable, and then having the incidence angles of the wing and tail be additional variables. 

I'll add some lines to D8_HT to clarify the original lines of code implemented, and will keep this issue open so we figure out the angle of incidence variables.

**Comment by mayork** [comment]
that's true, I was using thin airfoil theory and assuming there was no angle of incidence. If we account for angle of of incidence we should call the variable something different than alpha because AOA is just a ratio of free stream velocities. The new variable would be AOA + angle of incidence.

**Comment by 1ozturkbe** [comment]
I think another issue in integration might be this: 
```python
climb['C_{L_h}'] == 2*3.14*climb['\\alpha'],
cruise['C_{L_h}'] == 2*3.14*cruise['\\alpha'],
cruise['C_{L_h}'] <= 1.1*cruise['C_{L_{ah}}']*cruise['\\alpha'],
cruise['C_{L_h}'] >= 0.9*cruise['C_{L_{ah}}']*cruise['\\alpha'],
```
We are doubly constraining the horizontal tail lift coefficient. Perhaps we should only have the second set of constraints?

**Comment by 1ozturkbe** [comment]
Actually, it turns out that, if you comment out the first two, you get the same solution.

**Comment by 1ozturkbe** [comment]
It must be that the C_{l_{h}} is being set by some other equality constraint that is active.

**Comment by whoburg** [comment]
it seems to me that for an initial model we might want to assume that the htail CL can vary independently from the wing CL? (this is a fair assumption so long as there's a jackscrew to set the tail incidence (true for all commercial airplanes I know of) and assuming we're not looking at any fast transient dynamics)

**Comment by mayork** [comment]
I allows the HT CL to vary somewhat independently from the wing CL. It turns out it was important to bound the HT angle of attack, so I bounded it to be within 20% of the wing AOA which allows some independent variation of the tail CL. The 20% is obviously subject to discussion/improvement.

**Comment by 1ozturkbe** [comment]
I agree with@whoburg. I think it might be better just to not link the CLs of the two. Instead we could set the alphas independently, because of the jackscrew, so that the tail can operate at its optimal trim condition during all phases of flight. We should try solving without any of the \\alpha constraints that link the tail to the wing. I don't expect that the solution would suddenly break. I can try this later today.

**Comment by 1ozturkbe** [comment]
As of commit 96031eff, the HT CL is independent of wing CL in both D8_HT_simple_profile.py and CFP_Fuselage_Performance_int_ht.py. D8_HT is giving designs that make physical sense. Think we can close this.
