### ISSUE TITLE
RuntimeWarning: sum of nu^T * A did not vanish

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#17]
@bqpd is the above runtime warning the same as dual infeasible?

**Comment by bqpd** [comment]
It could, bUT MOSEK would probably have said if that were the case. This specifically means that all of the constraints sensitivities together don't sum to zero. Did you run into this in an SP?

**Comment by mayork** [comment]
yes i did. it flips between that and going unknown after a near feasible solve

**Comment by bqpd** [comment]
Hmm. It might be related to dual feasibility...does it solve with debug?

I should really make those errors optional so you could pass a "error_on_check=False" arg and see if it solved okay anyway.

**Comment by mayork** [comment]
interesting getting it at https://github.com/hoburg/d8/commit/f208537c6a6261fbbd49652587c5332e249af1e5 now. All the solves are primal feasible then it throws that warning

**Comment by bqpd** [comment]
What file?

**Comment by mayork** [comment]
`D8_engine_integration.py`

I commented out the warning and now it says `RuntimeWarning: Primal solution violates constraint: 1.00211157257 is greater than 1` so probably dual infeasible. I do think it would be worth while to be able to disable warning when you solve.

**Comment by bqpd** [comment]
I can't run that example because of a missing module: 

```
Traceback (most recent call last):
  File "D8_engine_integration.py", line 24, in <module>
    from TASOPT_engine import Engine
ImportError: No module named TASOPT_engine
Traceback (most recent call last):
  File "D8_engine_integration.py", line 24, in <module>
    from TASOPT_engine import Engine
ImportError: No module named TASOPT_engine
```

but I'm making a branch on gpkit which should get merged soon, where if you solve with `warn_on_check=True` it will just print out the first check warning instead of raising a RuntimeWarning, so that you can check it yourself.

**Comment by whoburg** [comment]
Did the `sum of nu^T * A did not vanish` warning occur with a status of OPTIMAL/PRIMAL_AND_DUAL_FEASIBLE? If so, that's quite interesting/concerning.

We ought to print out the sum of nu^T * A to debug nans vs small values.

**Comment by mayork** [comment]
no longer an issue so closing
