### ISSUE TITLE
Refining I_{z}

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#20]
This is a to do. 
Currently (commit 0b3b7f1) , the yaw moment of inertia is set using a substitution. 
```python
'I_{z}': 12495000, #estimate for late model 737 at max takeoff weight (m l^2/12)
```
Will need to refine this if we want to have better VT sizing, especially since engine out does not size the VT dimensions.

**Comment by mayork** [comment]
this a rough estimate of a 737 fuselage Iz, should be pretty easy to add some constrains that refine it

**Comment by 1ozturkbe** [comment]
I am in the process right now. I'll post the progress shortly.

**Comment by 1ozturkbe** [comment]
As of commit 668016431e8a3850169f954ceb26e6804842b795, has been integrated into CFP_Fuselage_Performance_int_HT. Can be ported over to other models as necessary. Not closing, so that we remember to put this in in the end.

**Comment by 1ozturkbe** [comment]
As of c002a5e, has been integrated into D8 for both the B737-800 and the D82. Can be refined in the future as needed. Closing!
