### ISSUE TITLE
Non-deterministic solves with engine integrated with other subsystems

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#21]
(This may be of particular interest to you @bqpd.)
Looking at commit e928c3624f, and running engine_flight_profile_integration.py, solved 2 out of 4 tries. 
Return samples: 
```python
Interior-point solution summary
  Problem status  : PRIMAL_AND_DUAL_FEASIBLE
  Solution status : OPTIMAL
  Primal.  obj: 9.5316444704e+000   Viol.  con: 1e-004   var: 0e+000 
  Dual.    obj: 9.5316452434e+000   Viol.  con: 0e+000   var: 2e-002 
* End solution on dual form. *
Transforming to primal solution.
Solving took 0.069 seconds.
result packing took 1.4e+02% of solve time
solution checking took 45% of solve time
Solving took 6 GP solves and 15 seconds.
```
and 
```python
Optimizer terminated. Time: 0.47    
Return code from optimize - 10000

Interior-point solution summary
  Problem status  : UNKNOWN
  Solution status : UNKNOWN
  Primal.  obj: -5.3807195063e+002  Viol.  con: 5e+003   var: 3e-002 
  Dual.    obj: -5.1518746080e+003  Viol.  con: 0e+000   var: 6e-005 
* End solution on dual form. *
Transforming to primal solution.
Solving took 0.478 seconds.
    result = solvefn(solver, verbosity, *args, **kwargs)
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\signomial_program.py", line 123, in localsolve
    result = primal_feas.solve(solver, verbosity=verbosity-1)
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\geometric_program.py", line 183, in solve
    (solvername, solver_out.get("status", None)))
RuntimeWarning: final status of solver 'mosek' was 'UNKNOWN', not 'optimal'.
```
Martin and I are thinking that some initial guesses in the model, esp. for the engine, may resolve the solve issues. Let us know if you have any ideas Ned; we will also post updates here.

**Comment by mayork** [comment]
@bqpd I was surprised the following code works

```phython
with Vectorize(2):
    x = Variable('x')
m = Model(sum(x), [x >= 1], x0={'x': 2})
```

is the initial guess for each index of x being set to 2?

**Comment by mayork** [comment]
also @whoburg this might interest you too...the code solves non-deterministically but it appears machine dependent...it never solves on my mac but solves on Berk's windows half the time. We have the same gpkit and numpy

**Comment by bqpd** [comment]
I created a model like this back when I was testing shopping models, and think I brought it up in group meeting...definitely a bad sign for the overall stability of your model! In my case I think it was some asymptotically close asymptotically flat constraints.

@mayork: yup! Actually that's the substitution for every variable named `x` to be initialized to 2, but in this case that seems to be the same thing. You could also do `x0={x: [2, 2]}` to get just that VectorVariable.

**Comment by 1ozturkbe** [comment]
@bqpd for resolving the 'asymptotic flatness', what would make the most sense? SP initial guesses? (flatness puts the effectiveness of guesses in getting convergence to doubt.) composite objective functions? Do you have any other suggestions? I think there are many constraints in the model that the objective is very insensitive to, which would make it very possible that we have 'flatness' in the model.

**Comment by bqpd** [comment]
On second though, my issue might have been that the cost was being driven along constraints that were either flat or vertical, so this issue just set an upper bound on the weights I had that were driving them to flat and vertical. It shouldn't be an issue with only flatness, I don't think.

Initial guesses worked for my case pretty well, so worth a try. Ultimately I think this means the model is numerically difficult, which might mean it needs a refactor, or worst-case means you need to scale some of your variables (probably to ~1 will work).

**Comment by mayork** [comment]
@bqpd I could get the model to solve reliably when I ran debug with relaxed constants abound bounded variables. What confused me was that the solution indicated relax was 1 for all constants and there were no variable at the bounds. The model will not solve when it is simply bounded. Also, when I run unbounded the first solve is primal dual feasible and near optimal. Does any of this indicate something about the model?

**Comment by bqpd** [comment]
Yes, I think so. Interesting!

**Comment by mayork** [comment]
I just verified that the engine and VT integrated together solve fine

**Comment by whoburg** [comment]
I fundamentally don't understand how anything in our code could be non-deterministic.

**Comment by mayork** [comment]
I think this correlates to doing a feasibility solve after a near optimal solution...although it is not clear why Mosek will sometimes return optimal and other times near_optimal. I assume the GP approximation to the first iteration of the same GP will always be the same, correct? If so, is this some weird machine precision effect?

**Comment by bqpd** [comment]
@whoburg, pretty sure it's not our code. I've seen this before with MOSEK and a very simple SP shopping model. (I think mentioned in group meeting and a comment in that draft paper last term as well)

**Comment by whoburg** [comment]
A MWE for a mosek model that has non-deterministic results sounds useful!

**Comment by bqpd** [comment]
I've got it sitting around somewhere...will put it in an issue on GPkit

**Comment by 1ozturkbe** [comment]
@bqpd,if you do not think that this is an issue from our side, please feel free to close it.

**Comment by bqpd** [comment]
(links to https://github.com/hoburg/gpkit/issues/1059)
