### ISSUE TITLE
TASOPT validation

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#22]
@mayork @bjarni177 Thought it would be a good idea to discuss here how to tackle running TASOPT, and getting the validation done. 
I have found it to be a huge challenge to get it to run on my Windows, but it seems not so difficult on Linux. I got it to compile on my Linux desktop in the ACDL cluster, and although it is having some issues, at least it compiles. 
I know you @bjarni177 made some progress as well, so I think we can aggregate our knowledge about running TASOPT here, instead of over email threads :)

**Comment by bjarni177** [comment]
Berk,

Keep in mind running tasopt on Linux and Mac should be very similar. I can meet you on Monday to help you compiling - if you haven’t managed to do so by then.

Cheers,
Bjarni Örn

**Comment by 1ozturkbe** [comment]
I unfortunately will not be in town Friday this week through next Sunday, but I'm sure Martin could use the help. I am also meeting Alex Feldstein to talk about running on Windows machines.

**Comment by bjarni177** [comment]
Martin, when do you want to meet up?

Alex should be able to help you - he’s resourceful 

Cheers,
Bjarni Örn

**Comment by 1ozturkbe** [comment]
Update from my meeting with Alex last week, we got TASOPT running on my Linux desktop in the ACDL cluster. Windows remains a mystery, but I am confident that we could set it up on your Macs with relative ease.

**Comment by bjarni177** [comment]
Whoop Whoop!

Great to hear that TASOPT is up and running.

Cheers,
Bjarni Örn

**Comment by 1ozturkbe** [comment]
I believe we have been able to get some TASOPT runs done, so we can close this.
