### ISSUE TITLE
wing fuel volume prohibits long range flights

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#23]
working on figuring out a fix

**Comment by 1ozturkbe** [comment]
What do you mean by 'long range'? Some specificity would be awesome, along with some sweeps. Also, which file are you running, on which commit?

**Comment by mayork** [comment]
its a file that is just the engine and the wing i'm keeping locally rn. it won't solve for ranges over 2200nm using the standard wing model. tweaking of the wing fuel volume constraints can remove the issue entirely so i'm working on figuring out the approximations used to make those constriants

**Comment by 1ozturkbe** [comment]
Hmmm, it might also be that the drag model is wonky; just make sure that it is reasonable. o/w the fuel volume model seems reasonable in CFP.

**Comment by mayork** [comment]
i don't think it is the drag model, drag coefficients are sitting at around .023 which is lower than a real 737. 

However, the wing area is coming out unrealistically small (50 m^2)

**Comment by mayork** [comment]
this was simply not true, the issue was the SP huerestic
