### ISSUE TITLE
Replicating TASOPT D8.0/D8.2 performance

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#25]
Since I have started trying to find discrepancies in the performances of the models, I felt it is important to document them thoroughly. So here we go. And anyone, feel free to weigh in.

**Comment by 1ozturkbe** [comment]
WEIGHT
- Missing weight metrics: Can see this in greater detail in TASOPT_weight_fractions.csv
- Consistent overprediction of bending reinforcement mass (both vertical and horizontal). Don't know the exact reasons for this. Investigating atm. 
- Consistent overprediction of wing weight; also alarming that we use a load factor of 2, not 3 [TAS]. Max load calculation at Vne is good, but perhaps we aren't getting something right? Distributed fuel load relief not considered, would help significantly. 
-Tail values relatively consistent.

**Comment by 1ozturkbe** [comment]
ENGINE - Mostly OK without detailed engine model
- BLI Benefit currently not considered; Tuesday's seminar should hopefully clarify.
- Need to find TSFC estimates from TASOPT to plug in. Also, a surrogate model would help as well. 
- Engine nacelle and pylon weight, as well as drag, completely missing.

**Comment by 1ozturkbe** [comment]
DRAG MODEL
- Total rubbish. Needs significant improvements.
- Possible find a good surrogate, or fit D8 wind tunnel data. I don't really know...
- Furthermore, need to better account for transonic drag. The drag rise seems off, and allows the aircraft to fly at (rarely) above M=1 for edge cases.

**Comment by mayork** [comment]
How far off are the drag numbers? The wing transonic drag rise a direct to fit to the data used in TASOPT. I would suspect going supersonic is an effect of the surrogate engine model where fuel burn increases linearly with trust.

**Comment by 1ozturkbe** [comment]
I meant mostly the fuselage drag model. The drag model actually predicts TASOPT quite well (L/D within 5%), so I suspect the rudimentary engine model is the reason. Good point.

**Comment by 1ozturkbe** [comment]
It would also make sense that the engine and pylon drag, when added, will bring the model closer to TASOPT (it is slightly optimistic in L/D atm).

**Comment by 1ozturkbe** [comment]
Figured out discrepancy in wing weight. TASOPT sizes for a load factor of 3 on MTOW. We size for a load factor of 2 for loading at VNE, which is hugely conservative. I will apply changes and see what happens.

**Comment by 1ozturkbe** [comment]
It is also important to note that the TASOPT wing loading also takes into account maximum downforce by the horizontal tail. Will account for as well.

**Comment by 1ozturkbe** [comment]
Interestingly enough, I do not find that TASOPT accounts for wing load relief due to distributed fuel load. I will be following their loading verbatim, and not integrating distributed weight.

**Comment by 1ozturkbe** [comment]
We are removing the yaw rate constraint, and the 1in20 rule that was present in the original VT sizing.

**Comment by mayork** [comment]
@1ozturkbe i think most things here have been resolves, can we close this and shift to #28?

**Comment by 1ozturkbe** [comment]
Agreed. Closing.
