### ISSUE TITLE
import engine directly from turbofan repo

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#26]
@bqpd what is the best way to do this? give turbofan an init so it's installable?

**Comment by bqpd** [comment]
yup, a `setup.py`! Then use `pip install -e` to install it. @mjburton11 knows the way.

This won't work with our repo testing immediately, but I think it might with just a little bit of a trick which we should test sometime.

**Comment by mayork** [comment]
fixed via commit 8dd5da142b4a78e25439
