### ISSUE TITLE
cruise climb on master

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#35]
@1ozturkbe is cruise climb working? I'm a little confused look at this output off of master 

```

In [5]: print sol('hft')
{hft_Mission.3, FlightState.9, Altitude.9: <Quantity([ 11000.57425275  22001.15804698  33001.74241755  33001.72275826
  37698.32081336], 'foot')>, hft_Mission.3, CruiseSegment.3, FlightState.11, Altitude.11: <Quantity([ 33001.72275826  37698.32081336], 'foot')>, hft_Mission.3, ClimbSegment.3, FlightState.10, Altitude.10: <Quantity([ 11000.57425275  22001.15804698  33001.74241755], 'foot')>}

In [6]: print sol('dhft')
{dhft_Mission.3, ClimbSegment.3, ClimbP.3: <Quantity([ 11000.57425275  11000.57425275  11000.57425275], 'foot')>, dhft_Mission.3, CruiseSegment.3, CruiseP.3: <Quantity([    6.09681429  4809.10931072], 'foot')>}
```

unless i'm wrong it's saying cruise segment has a 6 foot climb but there's an approx 4000 climb reflected in the actual altitude numbers

**Comment by 1ozturkbe** [comment]
That's perfect. The first dhft is trivial; it's just some relaxed value to make sure than h(cruise[0]) <= dhft(cruise[0]) +h(climb[-1]).

**Comment by mayork** [comment]
So then how are we accurately accounting for the increased thrust to climb? Because right now we're pegging the minimum RC value so I think we're essentially climbing for free

**Comment by 1ozturkbe** [comment]
Will fix.

**Comment by 1ozturkbe** [comment]
Took me forever to find why this wasn't working... it was because of the hftCruiseHold dummy variable. Fixing now, but since I have to run tons of plots and don't want to have to debug more UNKNOWNs, will be pushing to another branch (cruiseclimb).

**Comment by 1ozturkbe** [comment]
Getting near optimal. My goodness...

**Comment by bqpd** [comment]
Near optimal works on a recent pull request

**Comment by 1ozturkbe** [comment]
This is being resolved in the genVSP branch, and should be integrated into master shortly.

**Comment by 1ozturkbe** [comment]
As of commit 1ee7a94, cruise climb works fine! Closing.
