### ISSUE TITLE
weights now too low?

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#36]
@1ozturkbe any idea what changed and made us start missing most of the weights low by a lot?

**Comment by mayork** [comment]
i think this might go back to cruise climb not working right. i'll let you take a look tomorrow.

**Comment by 1ozturkbe** [comment]
Cruise climb works just fine. It's something else, just don't know why. I actually had to revert your Afuel code locally since I have to prep for my presentation on Tuesday as well. We should meet at some point tomorrow to talk about the slides.

**Comment by mayork** [comment]
i don't think cruise climb works the altitude build up returned in the solution doesn't make any sense look at https://github.com/hoburg/d8/issues/35

**Comment by 1ozturkbe** [comment]
poop. i should have been more careful. Will fix.

**Comment by 1ozturkbe** [comment]
Referring this issue to #35, and closing.
