### ISSUE TITLE
Multi-mission not working

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#42]
@1ozturkbe i was wondering if you could take a look at https://github.com/hoburg/d8/commit/8383429a61694e043c320ee01d128458be8e506c. It's the mutli-mission formulation with Nmission set to 1 so it should be the same as a normal solve but it isn't working and I have no idea why.

**Comment by 1ozturkbe** [comment]
I will take a look at it now. Sorry, been AWOL for the last few days; they have been crazy since I just got back in town.

**Comment by 1ozturkbe** [comment]
Btw, for some reason it says that there are ReqRng is a vector of length 4. Investigating...

**Comment by 1ozturkbe** [comment]
Btw, for the multimission, the only thing you change is the range, right? Or are you modulating the number of passengers as well? And also, why can't we pass vector substitutions  instead of doing the equality constraints?

**Comment by 1ozturkbe** [comment]
So I got it to solve, by literally doing one modification:
```python
ReqRng[0] == 3000 * units('nmi'),
#to
ReqRng[:Nmission] == 3000 * units('nmi'),
```
I don't see why this makes a difference, but when I do the following, I get some weeeeeiiird shit. 
```python
sol('ReqRng')
Out[10]: <Quantity([ 3000.  3000.  3000.  3000.], 'nautical_mile')>
sol('ReqRng')[:Nmission]
Out[12]: <Quantity([ 3000.], 'nautical_mile')>
```
Confusion? I think yes. Why are there 4 ReqRng values?

**Comment by 1ozturkbe** [comment]
HAHAHA I figured it out...
You have this on line 1232:
```python
    if multimission:
        m = Mission(Nclimb, Ncruise, Nmission = 4)
```
Lol, you set Nmission in the loop, and don't pull it from outside... Will push fix.

**Comment by 1ozturkbe** [comment]
With the latest code, I can't get the non multi-mission 737 to solve. Will push as soon as I get both working.

**Comment by 1ozturkbe** [comment]
Also, have you noticed that there is some weird g variable that pops up somehow from the Atmosphere model, although no such variable actually exists (to my knowledge? ). I'm so confused... I've been trying to track it down and just can't find it.

**Comment by mayork** [comment]
starting from the top:
- no idea why ReqRng has a length of 4 that's def a bug, excellent catch
- I'm currently only modulating range, will add passengers once range works reliably
- can't pass vector subs due to #37 and #40. To my knowledge #37 still doesn't have a good solution 
- push the code that isn't solving i think i know why (most likely a substitutions error, i changed some stuff and prob made an error) i'll take a look
- I'll look for the g I have some thoughts

**Comment by mayork** [comment]
let me know when you push that code

**Comment by 1ozturkbe** [comment]
Got pushed. ReqRng bug fixed.

**Comment by mayork** [comment]
now working, resolved
