### ISSUE TITLE
Consolidate test and main functions

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#45]
At least during development it would be WAY easier if the continuous integration tests ran from the main function instead of a test function so we aren't updating substitutions in two places. Is there a way to do this?

**Comment by bqpd** [comment]
Have main run your test function?

**Comment by mayork** [comment]
gosh that's obvious haha

**Comment by mayork** [comment]
I'll handle this at some point in the near future

**Comment by mayork** [comment]
fixed
