### ISSUE TITLE
D8 failing tests due to mosek_cli and cvxopt? 

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#46]
If we look at https://acdl.mit.edu/csi/job/gpkit_ResearchModel_d8_Push/310/ test results, there are multiple sections that fail tests due to some issues with cvxopt or mosek_cli. 
For eg. in macys, there is the following error message:
```python
Command '['mskexpopt', '/var/folders/2g/zj8kjvln2gn78qpr82fdqf7w0000gp/T/tmpJUGPFA/gpkit_mosek']' returned non-zero exit status 152
```
There are also errors due to UNKNOWNs or DUAL_INFEASIBLEs, but is it possible that D8 is also failing tests for other reasons as well?

**Comment by mayork** [comment]
@bqpd thoughts?

**Comment by bqpd** [comment]
try disabling those solvers and see if it passes?

**Comment by mayork** [comment]
lol @1ozturkbe you had taken `D8.py` out of `TESTS`...anyways, i fixed everything and we now pass tests. The only test is the 737-800 analysis model, can add more later

**Comment by 1ozturkbe** [comment]
Lol, my b. Thanks for taking care of this!
