### ISSUE TITLE
Removing engine specific variables from Aircraft and AircraftP in D8. 

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#48]
Hey @mayork, would it be possible to do this? I feel it is cluttering up D8 and also inconsistent with the hierarchy of the model.

**Comment by mayork** [comment]
give an example

**Comment by 1ozturkbe** [comment]
Snace, CDnace etc.

**Comment by mayork** [comment]
nacelle is not considered part of the engine so i'd rather leave it with the airframe

**Comment by 1ozturkbe** [comment]
Arrgghh it sticks out like a sore thumb to me... in the short term I will put up with my discomfort, since it is low priority.

**Comment by 1ozturkbe** [comment]
I'm going to close this issue, since I am better convinced now that the nacelle stuff belongs in the Aircraft class.
