### ISSUE TITLE
Call d8 subs from separate files. 

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#49]
This is an improvement to reduce clutter and try to avoid inconsistent substitutions. 
We should start pulling subs from external python files, and be able to see every single substitution for each aircraft (D82, b737800, 737ER, 777 etc.), without doing the subs.update business from D8.py.

**Comment by mayork** [comment]
yeah this is a good call, it'd solve the testing problem as well

**Comment by 1ozturkbe** [comment]
Btw Martin, thanks for the awesome work you have done on making this happen! I'm going to leave this open until we iron out all of the issues w.r.t the subs.

**Comment by mayork** [comment]
Seems like all the subs are working at the same level they were before (I just tested the other files). I'm fine to close whenever you are.

**Comment by mayork** [comment]
this is done, files are validating. closing now.
