### ISSUE TITLE
Speed issues - Constraint Relaxations

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#5]
Sweeping this model takes forever. First sweeps for SM (n=10) in CFP_Fuselage_Performance_int_HT took 82.5 seconds [cb63fa52]. What a tragedy... 

@mayork We need to identify opportunities to streamline the code and relax constraints (especially those pesky SignomialEqualities) continuously. As such, I thought it would be useful to create an issue where we can document places where we can shave off seconds in solver time, purely using constraint relaxations that do not alter the solutions, or the tightness of constraints. 

I suggest that, whenever we implement and push a relaxation of a constraint purely for speed improvement, we preceed the commit name with '[speedup]' so we can keep track of these easily. And also because it would be really cool to see which constraints we had relaxed towards the end of integration! Let me know what you think.

**Comment by bqpd** [comment]
I could implement autosweep for SPs, if you like. It would have the guaranteed bounds, but it would probably take half as many solves to produce a good guess...

**Comment by 1ozturkbe** [comment]
I don't really understand what autosweep actually does, but would be useful if you think it will reduce number of solves. If you could implement it I'd be down to dig into it.

**Comment by mayork** [comment]
I'm not sure the speed is really that great of a concern. I think we can speed it some but from what I've seen with engine code i don't think we're going to make any large speed improvements. Anyhow, of each full mission solves in about 13 seconds thags a massive speed improvement relative to tools like Tasopt. It's really quite impressive.

**Comment by 1ozturkbe** [comment]
I agree that it is impressive, and relatively speaking blows every other optimization framework out of the water. But why shouldn't we take the opportunity to make it faster when we can easily do so by relaxing constraints? Being able to do so also demonstrates that we fundamentally understand what pressures are acting on every variable, and that in itself is valuable. My primary concern is the Signomial Equalities. Not only are they slow to solve, but they are linked to difficulties to having the code converge (eg.  if you have a variable that is multiply constrained by SigEqs, it may prove problematic). Inequalities are strictly better than equalities in this respect. Does this better explain my line of thinking?

**Comment by mayork** [comment]
I agree with what you're saying. I just wanted to set expectations that I don't think we're going to get that big of an improvement (I did this to the engine and you can shave a few seconds but I don't we'll see like a factor of 2 improvement or something)

**Comment by 1ozturkbe** [comment]
Oh no, I don't expect that at all. There are benefits other than the runtime that make constraint relaxation useful. It's a win in all respects :)

**Comment by 1ozturkbe** [comment]
Have recently gotten some work done on this, esp. with SigEqs in the fuselage and tail sizing. This is a WIP.

**Comment by 1ozturkbe** [comment]
I have been scrubbing the model during the last few months, and it seems like we have done a pretty good job with this. The biggest culprit was the tail leading/trailing edge constraints, which were summarily removed. Closing.
