### ISSUE TITLE
all D8 models have relaxed constants at the final GP iteration

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#52]
@1ozturkbe this is not due to the subs, I checked. Any idea what is going on? Did you change the root moment constraints on the D8 and 737 type models?

**Comment by mayork** [comment]
could it be the buoyancy stuff?

**Comment by mayork** [comment]
could this do with the new wing sizing for landing load? 777 isn't solving without relaxed constants either and Drela said that he doesn't size the wing for landing

**Comment by 1ozturkbe** [comment]
@mayork Pretty certain it is not the buoyancy stuff, because this was occurring way in advance of adding that model. Definitely not a consequence of the wing landing model either; I will likely remove that today because it is not actually present in TASOPT. This is intriguing to me because the 73 is designed to land at max fuel, since it has no jettison system.

**Comment by mayork** [comment]
I think hunting this down needs to be top priority...it's gotta be one of the differences between 737 and D8

**Comment by 1ozturkbe** [comment]
After some testing, I believe that it is something to do with the solver. If I solve for the D82 with a reltol=0.01, the model solves, but at higher reltol's the model fails. @bqpd can you help us decipher what this may mean? I'm pretty certain at this point that the model is well formulated, and that all of the necessary substitutions are in place.

**Comment by 1ozturkbe** [comment]
Furthermore, I realize this happens when the initial objective value of the solver is much lower than the previous optimum, but rises rapidly during the solve to reach the previous optimal value. Perhaps some odd solver dynamics?

**Comment by mayork** [comment]
great work Berk this is certainly interesting...I hadn't even thought to look at the solver. I might try solving with cvxopt later (it'll take forever but might be interesting). For now, should we just set the higher reltol value and push on?

**Comment by 1ozturkbe** [comment]
I don't see any reason not to! Plus, lower reltol speeds up the solution speed, and means that we do not do a large number of iterations hopping around the optimal value like we used to.

**Comment by mayork** [comment]
closing this issue...tends to be caused by unrealistic subs, particularly in the CG
