### ISSUE TITLE
Fuselage height untight

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#57]
Tried basic fixes and failed to prevent. Not a huge priority (doesn't heavily affect design outcomes), but still concerning. Will post updates here.

**Comment by 1ozturkbe** [comment]
Still noticing this issue in the models... Will need to resolve soon.

**Comment by 1ozturkbe** [comment]
@mayork this is a significant issue... we still have cabin volume increasing beyond reason, because our drag model still doesn't have any penalty for increased volume. So wonky... I got in touch with Haofeng about doing MTflow stuff (he has already gotten it working on an Athena cluster), and I'm going to help him automate sweeps to do fits on. Should resolve this issue. Until this is done, I would not trust any of the results :/

**Comment by 1ozturkbe** [comment]
Also, noticed that subs were missing in D8_eng_wing for delta R_{fuse}. Should fix D8-type aircraft results. The tightness issue will keep showing up in conventional aircraft however.

**Comment by mayork** [comment]
i don't see what we set `delta R_{fuse}` to though.

**Comment by 1ozturkbe** [comment]
I set it to default 0.43m for D8-class aircraft. 0 for sweeps. And also, some of the subs aren't going through!? Anyways, gotta go to the IM game, but afterwards I'll keep trying.

**Comment by mayork** [comment]
I do not think that's legit. We need a systematic way to set it.

**Comment by 1ozturkbe** [comment]
It was just some issues with subs... I'll pull request everything from readthedocs over, then keep working on the docs.

**Comment by mayork** [comment]
so how are we setting DRfuse for the D8 class?

**Comment by 1ozturkbe** [comment]
for a general 8 SPR, just set to 0.43m default. Otherwise, not clear. For conventional A/C, its just 0. For D8's with other SPR, it might just make sense to scale with SPR.
