### ISSUE TITLE
Cvxopt vs. mosek performance for D8

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#58]
@mayork perhaps you should share your findings about solve times with cvxopt/mosek here, so @chriscourtin has some idea about the practicality of using cvxopt vs. mosek. I personally couldn't get cvxopt on a Windows machine to solve the b737 model overnight, so it might be a good idea to make moves for Chris to shift to mosek.

**Comment by mayork** [comment]
On my mac with cvxopt it took 111 minutest to solve the basic 737 model

**Comment by mayork** [comment]
I think this is a documented issue and there's nothing we can do about it. closing now.
