### ISSUE TITLE
VSP updates

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#59]
@1ozturkbe I'd like to see vsp for the 777esque D8, the D8 with the engine on the wings, and the D8 with the 737 engine

**Comment by 1ozturkbe** [comment]
Good idea, but I am really busy until Wednesday with Aviation paper. Will have to wait until afterwards. Btw, can you run VSP on your Mac at all?

**Comment by mayork** [comment]
haven't tried to set it up

**Comment by 1ozturkbe** [comment]
Update: works with all A/C I know of. Issues with horizontal tails for D8 configurations. Still trying to decide how to make sure engines under wings do not look wonky.

**Comment by mayork** [comment]
we should get 777 class and RJ class VSP

**Comment by 1ozturkbe** [comment]
Can do quickly, now that everything VSP is fixed. Should be up in 30 mins.

**Comment by 1ozturkbe** [comment]
This has been done. The RJ has a really small HT, not sure exactly why. Will check out.

**Comment by mayork** [comment]
i think we undersize HT cause we hit the min static margin where as TASOPT never hits it

**Comment by 1ozturkbe** [comment]
It's funny you say that, because the SM constraint is actually not tight. Our SM is 6.3%, whereas the min is 5%. Probably because of the min CL constraint on the HT.

**Comment by 1ozturkbe** [comment]
Another reason the tail looks small is because the fuselage is blocking part of it :P. Should I adapt the VSP to fix this issue? (I did it with the VT.)

**Comment by 1ozturkbe** [comment]
Actually, I'm just going to implement this, and regenerate the RJ plots, because they look quite wonky.

**Comment by mayork** [comment]
So in TASOPT the min static margin generally hovers around 0.3 so we're still a lot under

**Comment by mayork** [comment]
in the validation cases I set the static margin to the min in the TASOPT output so those tails match better, but for the morphing analysis I keep a constant 0.05

**Comment by 1ozturkbe** [comment]
I don't see any reason to match the 0.3 static margin, other than in the validation cases. This is great. You can let me know in this thread if more VSP updates are required. But for now, closing.
