### ISSUE TITLE
Sizing Variables to Aircraft(Model)

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#6]
Since variables like V_{NE}, and rho_0 appear in every single component (VT, HT, Fuselage), they should definitely moved to the Aircraft hyperclass. Same with xCG, xAC, especially since the equations concerning these variables appear in Aircraft() and AircraftP() anyways.

**Comment by 1ozturkbe** [comment]
As of cb63fa52, these haven't been fixed, as a reference.

**Comment by mayork** [comment]
good all i was thinking we needed to do this and hand't gotten around to it

**Comment by 1ozturkbe** [comment]
It has been done in CFP_Fuselage_Performance_int_HT, but not in other models. I'd appreciate it @mayork if you could do this for the HT, VT and Wing models. I believe I have already made some edits in HT to help in this respect.

**Comment by 1ozturkbe** [comment]
Any update on this @mayork? I remember you mentioning that you had been fixing the hierarchy.

**Comment by 1ozturkbe** [comment]
This has been completed, as of c002a5e1 (in the D8 submodels). Closing.
