### ISSUE TITLE
Failing tests on one machine

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#61]
@bqpd any idea what is going on here? Not clear why this one machine is failing tests while everything else is passing

https://acdl.mit.edu/csi/job/gpkit_ResearchModel_d8_Push/buildnode=reynolds-ubuntu16,optimizer=mosek/444/testReport/junit/gpkit.tests.from_paths/TestFiles/test_SP_aircraftpy_mosek/

**Comment by 1ozturkbe** [comment]
This is odd, because all of the tests are passing at the moment... but Ned let us know why this might be the case if you have ideas.

**Comment by bqpd** [comment]
looks like it's passing now?

**Comment by 1ozturkbe** [comment]
...no? Latest commit (1f7ae93e) still failing tests. It's odd; the error is a NEAR_OPTIMAL and then an UNKNOWN, whereas the model runs fine in every other machine...

**Comment by mayork** [comment]
sometimes the machine passes and sometimes it fails. very odd.

**Comment by bqpd** [comment]
Going to run it a few times and see if the failure is only on reynolds-ubuntu16 or what.

**Comment by bqpd** [comment]
Trial | Result
---  | ---
0 | Failure on reynolds-ubuntu16
1 | All passed
2 | All passed

**Comment by mayork** [comment]
is something wrong with that machine?

**Comment by bqpd** [comment]
Maybe so? It seems to be either inconsistent, gone, or only happens the first solve. (I'm still running more trials)

**Comment by bqpd** [comment]
Doesn't seem to be inconsistent...let me know if this happens when you do another push and we can see if it's a boundary condition or is just gone.

**Comment by mayork** [comment]
closing for now since we currently don't on Master..will reopen if observed again later
