### ISSUE TITLE
D8 config with BLI flies above min allowed cruise mach number

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#64]
optimal D8 flies at M 0.82 not 0.72 and the M 0.8 D8 flies at M = 0.9

**Comment by mayork** [comment]
UPDATE: Only the D8 models see this weird behavior...

**Comment by 1ozturkbe** [comment]
Whaaaa? The only reason I would understand this is if the engines preferred the higher total pressure... Do you see the same trend in D8 with podded engines (no BLI)?

**Comment by mayork** [comment]
yes same trend with rear podded engines

**Comment by 1ozturkbe** [comment]
D8 with wing engines flies at 0.76 for reference.

**Comment by mayork** [comment]
I'm going to note some key differences in the 737 and Mach 0.8 D8 flight profiles here:

- D8 ends cruise at 44k while 737 is 37k
- D8 climb rates are 2500, 1783, 786. 737 is 2500, 500, 500
-D8 climb M is .52, .69, .87 while 73 is .47, .56, .66
- each of the D8 cruise segments is 0.2 hours shorter and climb is shorter so overall flight is like 35 min less
- drag on the D8 is 6000N less despite the higher speed
- Wing profile drag coefficient is .009 for D8 and .006 for the 737 which makes sense
- D8 induced drag in cruise is .013 while 73 is .011...unsure what the discrepancy is
- D8 fuse Cd is .009 73 is .008
-D8 HT Cd is .006 73 is .0059
- VT cd equal to 3 sig figs
- D8 cruise FPR 1.7, 73 is 1.625
- LPC pressure ratio is ~6.2 for cruise D8 and ~4.8 for 73
- HPC pressure ratio is ~4.95 for 737 and 5.68 for D8
-D8 eng sys is 6666 lbf and 73 is 7900 lbf (largely due to different pylon weight fractions)
- 737 wing are is 10m^2 larger at 91.7 m^2
- D8 cruise Re: 25755206, 73 cruise Re: 24406273 (~5% difference)

Note that the input "on design" OPR is equal for the two aircraft so the differences are largely due to internal optimization

**Comment by mayork** [comment]
@1ozturkbe let me know your thoughts about this? I'm really not sure if this is a bug or a result or what.

**Comment by mayork** [comment]
are we using the extra fuselage lift to fly higher and then faster due to lower drag? This may be a legit result...

**Comment by 1ozturkbe** [comment]
The D8 fuselage lift fraction is higher, but its drag coefficient is also higher by about the same factor. It is likely that the D8 experiences higher benefit from a smaller wing because of this (because CDi goes with CL^2 whereas the fuselage drag goes with S (linear vs. quadratic). It would surprise me if this was the reason. Could easily test by setting the fuselage lift and drag coefficients equal for the two and rerunning.

**Comment by 1ozturkbe** [comment]
What is equally puzzling to me is that this phenomenon does not occur with D8_eng_wing, whereas it occurs with every other configuration in the D8 family. So odd.

**Comment by mayork** [comment]
Going to note heee to check the results of rear podded D8 altitude and compare to full D8...one effect could be lower external static pressure helping engine performance with BLI active

**Comment by mayork** [comment]
@1ozturkbe check this out
[M08_D8_wing_profile_drag.pdf](https://github.com/hoburg/d8/files/986771/M08_D8_wing_profile_drag.pdf)
It looks extremely reasonable

**Comment by mayork** [comment]
rear podded (no BLI) D8 does fly slower (M=0.87) and only goes up to ~40,000'

**Comment by mayork** [comment]
interesting altitude profile for the M08_D8...
![figure_1](https://cloud.githubusercontent.com/assets/6796415/25855544/77287338-34a1-11e7-89bb-67bb9dc0fc36.png)

**Comment by mayork** [comment]
here it is for the 737-800
[Screen Shot 2017-05-09 at 10.24.54 AM.PDF](https://github.com/hoburg/d8/files/986932/Screen.Shot.2017-05-09.at.10.24.54.AM.PDF)

and here it is for the M08 D8 with engines under the wing
[Screen Shot 2017-05-09 at 10.27.06 AM.PDF](https://github.com/hoburg/d8/files/986939/Screen.Shot.2017-05-09.at.10.27.06.AM.PDF)

and here it is for the M08 D8 with rear podded engines
![figure_1](https://cloud.githubusercontent.com/assets/6796415/25855881/5e43d276-34a2-11e7-903c-b1fb55637554.png)

**Comment by mayork** [comment]
So we can force the cruise mach number to be 0.8. If we do that we get this flight profile
![figure_1](https://cloud.githubusercontent.com/assets/6796415/25856903/5f44c39e-34a5-11e7-88f8-a46d16223e1b.png)

cruise reynolds number drops to: 21240186
climb rates become 2500, 1229, 790

**Comment by mayork** [comment]
@1ozturkbe should we just hard set the speed? It's not a huge fuel savings...

**Comment by mayork** [comment]
it isn't tail drag..
[M08_D8_VT_profile_drag.pdf](https://github.com/hoburg/d8/files/990143/M08_D8_VT_profile_drag.pdf)

I'll now try and implement Woody's suggested fuselage drag model

**Comment by 1ozturkbe** [comment]
K. Just to let you know, it is my goal to remove the fBLI drag correction today/tomorrow in favor of some approximation of fuselage BL defect ingestion.

**Comment by 1ozturkbe** [comment]
This will augment the Mach drag rise that hopefully will come from coupling the wing and fuselage drag models. But my updates pend the nomial_math issues...

**Comment by mayork** [comment]
if we can do that, cool...but I think the main concern here was the link between fuselage drag and wing area not the way we were handling D8 drag reduction

**Comment by 1ozturkbe** [comment]
yeah for sure, but it is also super sketchy that we have a BLI drag reduction that in no way depends on the engine parameters or the flow around the body. I think I can make all of these come together in a way that makes sense.

**Comment by mayork** [comment]
the simple drag model Woody suggested won't work because of how we take into account the wing sweep mach reduction...working on a new solution now

**Comment by mayork** [comment]
UPDATE: after https://github.com/hoburg/d8/commit/5f1b370f2743efff07aa2c32292e9ac3f662e178 we still fly at slightly over M=0.84 for the Mmin = 0.8 D8 case

**Comment by mayork** [comment]
interesting note, after the commit mentioned above only the D8 with BLI flies above the min mach number, everything else flies at the Mcruisemin.

The M=0.72 D8 wants to fly at M=0.78.

Here are plots for the M=0.8 D8
[M08_D8_altitude_profile.pdf](https://github.com/hoburg/d8/files/990762/M08_D8_altitude_profile.pdf)
[M08_D8_fuse_drag.pdf](https://github.com/hoburg/d8/files/990759/M08_D8_fuse_drag.pdf)
[M08_D8_HT_profile_drag.pdf](https://github.com/hoburg/d8/files/990761/M08_D8_HT_profile_drag.pdf)
[M08_D8_VT_profile_drag.pdf](https://github.com/hoburg/d8/files/990763/M08_D8_VT_profile_drag.pdf)
[M08_D8_wing_profile_drag.pdf](https://github.com/hoburg/d8/files/990760/M08_D8_wing_profile_drag.pdf)
This all looks legit to me. Next thing i'm going to do is dig into the engine

**Comment by 1ozturkbe** [comment]
Just as a clarification, now Cdfuse is based on Rfuse? Wouldn't it have been better to have based it on Afuse?

**Comment by mayork** [comment]
Didn't realize Afuse is a variable...right now it is based on l_fuse * R_fuse

**Comment by 1ozturkbe** [comment]
Afuse is a cross-sectional parameter, which would simulate a kind of form factor in a drag model. Potentially useful.

**Comment by mayork** [comment]
oh true I didn't consider that...I scaled off of L and R in an attempt to account for increased BL growth along a long fuselage...I suspect it is not overly relevant which option is used?

**Comment by 1ozturkbe** [comment]
Actually, I think if you divide the coefficient by a factor of Rfuse, and put Rfuse^2 into the drag model, it would improve it already.

**Comment by 1ozturkbe** [comment]
But the principle is this model here:
![image](https://cloud.githubusercontent.com/assets/15684191/25914446/550ec7b6-358c-11e7-87d7-96f89c3bc6cc.png)

**Comment by mayork** [comment]
where is that from?

**Comment by 1ozturkbe** [comment]
http://www.ae.metu.edu.tr/~ae451/lecture11_aerodynamics.pdf

**Comment by mayork** [comment]
@1ozturkbe pull engine, fixed a small typo in a fit. Although it appears to change little.

**Comment by mayork** [comment]
I did some digging in the engine, didn't see anything that looked off except for that typo i fixed in one spot (which i why I said to pull)...

**Comment by mayork** [comment]
I think i might have solved this...getting deep into the engine code right now

**Comment by mayork** [comment]
@1ozturkbe pull engine. the M 0.8 case now flies at the min and 0.72 case flies at 0.725. I'm good closing this if you are.

**Comment by 1ozturkbe** [comment]
What's the update in the engine, I'm curious?

**Comment by mayork** [comment]
this
```python
            fanmap = [
                self.engineP['\pi_f']*(1.7/self.fanmap['\pi_{f_D}']) == (1.05*self.engineP['N_f']**.0871)**10,
                (self.engineP['\pi_f']*(1.7/self.fanmap['\pi_{f_D}']))**.1 <= 1.1*(1.06 * (self.engineP['m_{tild_f}'])**0.137),
                (self.engineP['\pi_f']*(1.7/self.fanmap['\pi_{f_D}']))*.1 >= .9*(1.06 * (self.engineP['m_{tild_f}'])**0.137),
```
became this

```python
            fanmap = [
                self.engineP['\pi_f']*(1.7/self.fanmap['\pi_{f_D}']) == (1.05*self.engineP['N_f']**.0871)**10,
                (self.engineP['\pi_f']*(1.7/self.fanmap['\pi_{f_D}'])) <= 1.1*(1.06 * (self.engineP['m_{tild_f}'])**0.137)**10,
                (self.engineP['\pi_f']*(1.7/self.fanmap['\pi_{f_D}'])) >= .9*(1.06 * (self.engineP['m_{tild_f}'])**0.137)**10,
```

I had put the fit exponent on the wrong side but only in the fan map which allowed like a 2.5x variation in FPR instead of a plus minus 10% variation in FPR

**Comment by mayork** [comment]
yep. The fuselage drag change also contributed to fixing this...scaling off of fuselage area drop mach by .02, scaling the drag with mach another .02, and the final .02 was from the engine bug. Curious that only the D8 seemed to take advantage of the extra FPR variation. Anyways, closing this now.
