### ISSUE TITLE
Introducing PRFC optimization

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#67]
@mayork this is a heads-up that I am adding a new objective function for payload-range fuel consumption. For this objective, we remove the ReqRng and n_{pax} substitutions, and let the model figure out what the optimal mission is for the given configuration. it's a work in progress (I got a pretty funny result for the first solve with D8_eng_wing, but the results should be valuable).

**Comment by 1ozturkbe** [comment]
As a teaser, here is the VSP image of the solve (with set npax and ReqRng
![prfcd8](https://cloud.githubusercontent.com/assets/15684191/25917478/36fea69c-3596-11e7-8e87-344c833b4d13.png)
):

**Comment by 1ozturkbe** [comment]
Oh, because there is no y_{eng} sub in D8_eng_wing. I think your merge conflict overwrote my fix :P Will add again.

**Comment by mayork** [comment]
oh shoot, sorry!

**Comment by mayork** [comment]
this looks really neat! @1ozturkbe do you want to meet up tomorrow and outline what we want to present Tuesday?

**Comment by 1ozturkbe** [comment]
Sounds good. I'm free pretty much all day, but I would prefer the afternoon. I can also meet today if you are free; before 1pm works best.

**Comment by 1ozturkbe** [comment]
I want to keep this issue open until we resolve the vector subs issues. Currently, we have to comment out the n_{pax} 'substitution' equations within D8.py to be able to run with a PRFC objective. Hopefully we should no longer have to do this soon.

**Comment by mayork** [comment]
tomorrow is best for me. There's a chance we might fly JHO saturday so I'd need to verify the plane is ready in the late afternoon..how's 1pm?

**Comment by 1ozturkbe** [comment]
Cool, let's do it.

**Comment by mayork** [comment]
@bqpd could you give us an example of the right way to do one of these vector subs?

**Comment by bqpd** [comment]
What you were doing before should work fine! `[5*units("m")]`. `np,array([1, 2, 3])*units("m")` should also work.

**Comment by 1ozturkbe** [comment]
Cool, will implement this.

**Comment by 1ozturkbe** [comment]
I can't get the subs to work with BCS or relaxed_constants. I created new branch vectorsubs until we can resolve this, because I can't run any of the models with the recent changes I made.

**Comment by mayork** [comment]
@1ozturkbe can we close this since it isn't really an issue?

**Comment by 1ozturkbe** [comment]
I guess the issue is in vector substitutions, and PRFC works anyways. CLosing.

**Comment by bqpd** [comment]
Hmm, it worked with the example code @mayork posted. I'll add an issue.
