### ISSUE TITLE
777 BLI benefit low

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#71]
as seen on morphing charts

**Comment by mayork** [comment]
@1ozturkbe  can you take a look at this? I don't have any good answers

**Comment by 1ozturkbe** [comment]
Sure, will do. Will get back to you.

**Comment by 1ozturkbe** [comment]
Are you looking at max optimal or standard?

**Comment by mayork** [comment]
standard...really just concerned about the step where BLI is added

**Comment by mayork** [comment]
we still do well for the 737 using the same method. As best as i can tell our propulsive efficiency is also increasing when we add BLI despite the negligible fuel burn benefit

**Comment by 1ozturkbe** [comment]
btw, which version of gpkit are you running? the latest commit is not working...

**Comment by mayork** [comment]
i haven't updated since that time you did and it broke everything

**Comment by 1ozturkbe** [comment]
Could you specify the commit? I don't have it any more :P

**Comment by 1ozturkbe** [comment]
Nvm, found it.

**Comment by mayork** [comment]
i think it's this https://github.com/hoburg/gpkit/commit/4cce21bc7e42f816d65f62164162cc681f066321

**Comment by 1ozturkbe** [comment]
This is ridiculous, my Mosek has decided that it does not want to work any more. I will get back to you when I make progress...

**Comment by 1ozturkbe** [comment]
Finally got mosek to work again. No idea why it was acting up; I ended up building the python-only version from git. But anyways, will let you know if I have some insight.

**Comment by mayork** [comment]
resolved, issue was not properly accounting for drop in nacelle drag

**Comment by 1ozturkbe** [comment]
Glad. I guess we can close then!
