### ISSUE TITLE
Odd behavior in VT model (D8_VT_yaw_rate...)

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/d8#9]
@mayork The VT is behaving erratically. I don't know what has changed last, but check out commit a34976b. The aspect ratio goes way under 1; the model will need to be debugged. 
Otherwise, all models have been integrated in CFP_fuselage_performance_int_ht. I will move this into a new file called CFP_noengine.py once the vertical tail issues are fixed. Let me know when you take a look.

**Comment by mayork** [comment]
alright i'll take a look at it. i think a constraint on the height of the VT is probably required (for engine clearance)

**Comment by mayork** [comment]
is it dropping below 1 during a specific sweep? running with default the AR of the VT is 3 which still seems a little low but not as bad as under 1

**Comment by mayork** [comment]
is there a substitution for the VT AR?

**Comment by 1ozturkbe** [comment]
No, but I put A_{vt} >= 3 to stop it having an aspect ratio of 0.3. And also, with an AR of 3 it doesn't make sense, since the root chord is 14 m.

**Comment by 1ozturkbe** [comment]
It might have to do with the taper ratio substitutions. If you sub it, since the tail has linear taper, setting the aspect ratio sets the root chord. We should relax the taper substitution.

**Comment by 1ozturkbe** [comment]
Actually, there is no taper sub in VT, only in HT. I will keep digging.

**Comment by 1ozturkbe** [comment]
I have partially circumvented this problem by setting a minimum span constraint in CFP (as of 93cbc333). 
I think that the engine out condition makes a large VT that ends up having a pretty big max loading, driving AR down for structural efficiency purposes. This means that either (1) we aren't capturing the aero effects of a low-AR VT, or (2) there seems to be low-hanging fruit in having low AR tails. It's not clear to me which is more likely, but we are getting tails with huge root chords (around 14m) (tons of viscous drag), which the model perhaps doesn't predict. your thoughts @mayork?

**Comment by mayork** [comment]
i think we're missing aero effects. i could see the structural efficiency of the low AR being much higher just due to the low root moment. the reason this would be sub-optimal in real life is the rudder would be really long and i think there'd be massive separation problems when you applied the rudder. I'm not sure what the right way to fix this is. We could apply an AR constraint or perhaps attempt to set a max rudder chord and then compute the tails max CL with some simple relation that assumes a max allowable delta (probably 30 degrees in a landing configuration). Thoughts?

We also need the HT to clear the engines.

**Comment by 1ozturkbe** [comment]
I already make sure of the engine clearance, set AR constraints, and set a max root chord to stop the growth of the root, at the time of the previous comment. It is more well behaved, but results in still beefy tails. I think the engine out constraints just result in tails that are way too large, meaning that the max loading is also very large. The trends make sense; it is simply the result of the sizing condition we are using.

**Comment by 1ozturkbe** [comment]
Confirming that VT behaves as expected, and closing.
